version: '3.8'

services:
  monopostgres:
    image: postgres:17-alpine
    container_name: monopostgres
    volumes:
      - ./docker/postgres-data:/data
      - monopostgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - mononetwork

volumes:
  monopostgres-data:

networks:
  mononetwork:
    name: mononetwork
